### ISSUE TITLE
wrong final key words on entity Product

### ISSUE THREAD

**Issue by vipcxj** [MartinanderssonDotcom/java-ee-concepts#1]
The getter method of entity 'Product' was decorated by key word 'final'. As a result, container can not make a proxy for this method, The test "findSingle_noTx_usingGetReference" and "findSingle_useTx_usingGetReference" in "QueryingForEntitiesTest" lead to a wrong result.

**Comment by MartinanderssonDotcom** [comment]
Nice!

I did some changes to related files. However, GlassFish still fail `findSingle_noTx_usingGetReference` because oddly enough, GlassFish think the reference is managed which is a very clear violation of the spec.
